#!/usr/bin/env python3

from typing import Optional
from typing_extensions import Annotated
from cli import drone, snowplow, display

import typer
import os
import cli.log as log


app = typer.Typer(no_args_is_help=True)


app.add_typer(drone.app, name="drone")
app.add_typer(snowplow.app, name="snowplow")
app.add_typer(display.app, name="display")


def delete_data_callback(value: bool) -> None:
    if value:
        if os.path.exists("data/districts.pkl"):
            log.info("Deleting data/ditricts.pkl")
            os.remove("data/districts.pkl")
        if os.path.exists("data/routes.pkl"):
            log.info("Deleting data/routes.pkl")
            os.remove("data/routes.pkl")
        if os.path.exists("data/snow.pkl"):
            log.info("Deleting data/snow.pkl")
            os.remove("data/snow.pkl")
        raise typer.Exit()


@app.callback()
def main(
    delete_data: Annotated[
        Optional[bool],
        typer.Option(
            "--delete-data",
            callback=delete_data_callback,
            help="Remove saved data.",
        ),
    ] = None
) -> None:
    pass


if __name__ == "__main__":
    app()
