#!/usr/bin/env python3

import typer
from cli import drone, snowplow, display


app = typer.Typer(no_args_is_help=True, add_completion=False)


app.add_typer(drone.app, name="drone")
app.add_typer(snowplow.app, name="snowplow")
app.add_typer(display.app, name="display")


if __name__ == "__main__":
    app()
